const menus = [
  { id: 'tantanmen', name: '탄탄멘', emoji: '🍜', tag: '면요리 · 뜨끈한 국물', desc: '고소한 땅콩 소스와 얼큰한 육수의 완벽한 밸런스.', price: '11,000', time: '15분', filter: 'noodle' },
  { id: 'jeyuk', name: '제육볶음', emoji: '🥘', tag: '한식 · 매콤한 한 끼', desc: '달큰하고 매콤한 양념에 볶아낸 오늘의 밥도둑.', price: '10,000', time: '12분', filter: 'korean' },
  { id: 'chicken-salad', name: '치킨 샐러드', emoji: '🥗', tag: '가볍게 · 산뜻한 한 끼', desc: '바삭한 닭고기와 신선한 채소로 오후까지 가볍게.', price: '9,500', time: '10분', filter: 'light' },
  { id: 'tomato-pasta', name: '토마토 파스타', emoji: '🍝', tag: '양식 · 기분 전환', desc: '진한 토마토 소스와 바질 향이 기분까지 환기해줘요.', price: '12,000', time: '18분', filter: 'western' },
  { id: 'sushi', name: '초밥 모둠', emoji: '🍣', tag: '일식 · 깔끔한 맛', desc: '오늘은 다양한 한 점으로 산뜻하게 시작해보세요.', price: '14,000', time: '20분', filter: 'light' }
];
const miniMenus = [{ name: '소불고기 덮밥', id: 'bulgogi-bowl', emoji: '🍛', meta: '든든하게 · ₩10,000' }, { name: '김치찌개', id: 'kimchi-stew', emoji: '🍲', meta: '한식 · ₩9,000' }, { name: '타코 플래터', id: 'taco-platter', emoji: '🌮', meta: '새로운 맛 · ₩12,000' }];
const $ = (selector) => document.querySelector(selector);
const visitorId = localStorage.getItem('lunch-visitor-id') || (crypto.randomUUID ? crypto.randomUUID() : `visitor-${Date.now()}-${Math.random().toString(36).slice(2)}`); localStorage.setItem('lunch-visitor-id', visitorId);
const supabaseConfig = window.SUPABASE_CONFIG || {}; const supabaseClient = supabaseConfig.url && supabaseConfig.anonKey && window.supabase ? window.supabase.createClient(supabaseConfig.url, supabaseConfig.anonKey) : null;
const localFavorites = JSON.parse(localStorage.getItem('lunch-favorites') || '{}');
function renderMini() { $('#mini-grid').innerHTML = miniMenus.map((m) => `<article class="mini-card"><div class="mini-emoji">${m.emoji}</div><div class="mini-card-copy"><b>${m.name}</b><small>${m.meta}</small></div><button class="mini-save heart-action" data-menu-id="${m.id}" aria-label="${m.name} 저장" aria-pressed="false">♡ <small class="favorite-count">${localFavorites[m.id]?.count || 0}</small></button></article>`).join(''); syncFavoriteButtons(); }
function pick(menu) { $('#menu-emoji').textContent = menu.emoji; $('#menu-name').textContent = menu.name; $('#menu-tag').textContent = menu.tag; $('#menu-desc').textContent = menu.desc; $('.menu-stats span').innerHTML = `₩ ${menu.price} <small>예상 가격</small>`; $('.menu-stats span:nth-child(3)').innerHTML = `⚡ ${menu.time} <small>추천 소요시간</small>`; $('.save-btn').dataset.menuId = menu.id; syncFavoriteButtons(); }
function randomPick() { const filter = document.querySelector('.pill.active')?.dataset.filter || 'all'; const pool = filter === 'all' ? menus : menus.filter((m) => m.filter === filter); pick(pool[Math.floor(Math.random() * pool.length)]); }
function setTab(tab) { document.querySelectorAll('.tab').forEach((item) => item.classList.toggle('active', item === tab)); document.querySelector('.tab-line').style.left = tab.textContent.includes('인기') ? '98px' : '0'; if (tab.textContent.includes('인기')) pick(menus[1]); }
document.querySelectorAll('.tab').forEach((tab) => tab.addEventListener('click', () => setTab(tab)));
document.querySelectorAll('.pill').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.pill').forEach((item) => item.classList.remove('active')); button.classList.add('active'); randomPick(); }));
document.querySelectorAll('.mood-option').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.mood-option').forEach((item) => item.classList.remove('selected')); button.classList.add('selected'); $('#mood-face').textContent = button.dataset.mood === '가볍게' ? '🌿' : button.dataset.mood === '스트레스 해소' ? '🌶️' : '🙂'; }));
async function toggleFavorite(button) { const menuId = button.dataset.menuId; let result; if (supabaseClient) { const response = await supabaseClient.rpc('toggle_menu_favorite', { p_menu_id: menuId, p_visitor_id: visitorId }); if (!response.error) result = response.data; } if (!result) { const saved = !localFavorites[menuId]?.saved; const count = Math.max(0, (localFavorites[menuId]?.count || 0) + (saved ? 1 : -1)); result = { saved, count }; localFavorites[menuId] = result; localStorage.setItem('lunch-favorites', JSON.stringify(localFavorites)); } document.querySelectorAll(`[data-menu-id="${menuId}"]`).forEach((item) => { item.setAttribute('aria-pressed', String(result.saved)); item.classList.toggle('is-saved', result.saved); item.innerHTML = `${result.saved ? '♥' : '♡'} <small class="favorite-count">${result.count}</small>`; }); }
function syncFavoriteButtons() { document.querySelectorAll('.heart-action, .save-btn').forEach((button) => { const state = localFavorites[button.dataset.menuId]; if (state) { button.classList.toggle('is-saved', state.saved); button.setAttribute('aria-pressed', String(state.saved)); const count = button.querySelector('.favorite-count'); if (count) count.textContent = state.count; } }); }
document.addEventListener('click', (event) => { const button = event.target.closest('.heart-action, .save-btn'); if (button) toggleFavorite(button); });
$('#randomize').addEventListener('click', () => { randomPick(); const card = document.querySelector('.recommend-card'); card.classList.remove('is-changing'); requestAnimationFrame(() => card.classList.add('is-changing')); }); $('#shuffle-mini').addEventListener('click', () => { miniMenus.push(miniMenus.shift()); renderMini(); }); renderMini();
