create table if not exists public.menu_favorites (
  id bigint generated by default as identity primary key,
  menu_id text not null,
  visitor_id text not null,
  created_at timestamptz not null default now(),
  unique (menu_id, visitor_id)
);

alter table public.menu_favorites enable row level security;

create or replace function public.toggle_menu_favorite(p_menu_id text, p_visitor_id text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  saved boolean;
  total integer;
begin
  if exists (select 1 from public.menu_favorites where menu_id = p_menu_id and visitor_id = p_visitor_id) then
    delete from public.menu_favorites where menu_id = p_menu_id and visitor_id = p_visitor_id;
    saved := false;
  else
    insert into public.menu_favorites (menu_id, visitor_id) values (p_menu_id, p_visitor_id);
    saved := true;
  end if;
  select count(*)::integer into total from public.menu_favorites where menu_id = p_menu_id;
  return json_build_object('saved', saved, 'count', total);
end;
$$;

grant execute on function public.toggle_menu_favorite(text, text) to anon, authenticated;
