import { useState } from "react";
import { STAGES } from "../../lib/stages";
import type { WorkflowCycle } from "../../lib/types";

export function Dashboard({ cycle, onSelectStage }: { cycle: WorkflowCycle; onSelectStage: (id: number) => void }) {
  const [detail, setDetail] = useState<"amount" | "volume" | "risk" | null>(null);
  const deviceAmount = cycle.deviceRecommendations.reduce((sum, row) => sum + row.amount, 0);
  const optionAmount = cycle.optionRecommendations.reduce((sum, row) => sum + row.amount, 0);
  const totalAmount = deviceAmount + optionAmount;
  const totalQty = cycle.deviceRecommendations.reduce((sum, row) => sum + row.orderQty, 0) + cycle.optionRecommendations.reduce((sum, row) => sum + row.orderQty, 0);
  const risks = cycle.deviceRecommendations.filter((row) => row.result !== "정상").length + cycle.optionRecommendations.filter((row) => row.result !== "정상").length;
  const activeStage = cycle.currentStage;
  return <div className="dashboard-page">
    <section className="hero-card">
      <div className="hero-glow hero-glow-one" /><div className="hero-glow hero-glow-two" />
      <div className="hero-copy"><div className="eyebrow light">SCM CONTROL CENTER · 2026.08</div><h2>발주부터 입고까지,<br /><span>한눈에 보는 업무 현황</span></h2><p>수요 확정부터 PO Match까지 현재 Cycle의 진행상태를 확인하고 다음 업무로 이동하세요.</p><button className="hero-button" onClick={() => onSelectStage(activeStage)}>현재 업무 계속하기 <span>→</span></button></div>
      <div className="hero-orbit"><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><div className="orbit-core"><strong>{Math.round(((activeStage + 1) / STAGES.length) * 100)}%</strong><span>진행률</span></div></div>
    </section>
    <section className="luxury-metrics">
      <button className="luxury-metric accent clickable" onClick={() => setDetail("amount")}><span className="metric-kicker">발주금액</span><strong>{totalAmount.toLocaleString("ko-KR")}<small>원</small></strong><span className="metric-caption">클릭하여 산출근거</span><i>↗</i></button>
      <button className="luxury-metric clickable" onClick={() => setDetail("volume")}><span className="metric-kicker">발주수량</span><strong>{totalQty.toLocaleString("ko-KR")}<small> EA</small></strong><span className="metric-caption">클릭하여 산출근거</span><i>◒</i></button>
      <button className="luxury-metric clickable" onClick={() => setDetail("risk")}><span className="metric-kicker">검토항목</span><strong className={risks ? "risk-number" : ""}>{risks}<small>건</small></strong><span className="metric-caption">클릭하여 목록 확인</span><i>!</i></button>
    </section>
    {detail && <section className="detail-panel"><div className="detail-head"><div><div className="eyebrow">DETAIL VIEW</div><h3>{detail === "amount" ? "발주금액 산출근거" : detail === "volume" ? "발주수량 산출근거" : "검토항목 상세"}</h3></div><button className="close-button" onClick={() => setDetail(null)}>닫기 ×</button></div>{detail === "amount" && <><div className="detail-total">{totalAmount.toLocaleString("ko-KR")}원</div><div className="detail-list"><button onClick={() => onSelectStage(3)}><span>기기 발주금액</span><strong>{deviceAmount.toLocaleString("ko-KR")}원</strong><small>기기 발주량 화면에서 상세 보기 →</small></button><button onClick={() => onSelectStage(4)}><span>옵션·부품 발주금액</span><strong>{optionAmount.toLocaleString("ko-KR")}원</strong><small>옵션 발주량 화면에서 상세 보기 →</small></button></div></>}{detail === "volume" && <><div className="detail-total">{totalQty.toLocaleString("ko-KR")} EA</div><div className="detail-list"><button onClick={() => onSelectStage(3)}><span>기기 제안 발주량</span><strong>{cycle.deviceRecommendations.reduce((sum, row) => sum + row.orderQty, 0).toLocaleString("ko-KR")} EA</strong><small>기기 발주량 화면에서 상세 보기 →</small></button><button onClick={() => onSelectStage(4)}><span>옵션·부품 제안 발주량</span><strong>{cycle.optionRecommendations.reduce((sum, row) => sum + row.orderQty, 0).toLocaleString("ko-KR")} EA</strong><small>옵션 발주량 화면에서 상세 보기 →</small></button></div></>}{detail === "risk" && <div className="risk-list">{cycle.deviceRecommendations.concat(cycle.optionRecommendations).filter((row) => row.result !== "정상").map((row) => <button key={row.id} onClick={() => onSelectStage(row.code.startsWith("PRT") ? 3 : 4)}><span className="badge warn">검토</span><strong>{row.name}</strong><small>{row.result} · {row.code}</small><em>이동 →</em></button>)}</div>}</section>}
    <section className="dashboard-section-head"><div><div className="eyebrow">WORKFLOW JOURNEY</div><h3>업무 진행 단계</h3></div><span className="sample-pill">SAMPLE CYCLE · {cycle.baseMonth}</span></section>
    <section className="timeline-card"><div className="timeline-track" />{STAGES.map((stage) => { const state = cycle.stageStates[stage.id]; const done = state === "complete"; const current = activeStage === stage.id; return <button key={stage.id} className={`timeline-step ${done ? "complete" : ""} ${current ? "current" : ""}`} onClick={() => onSelectStage(stage.id)}><span className="timeline-node">{done ? "✓" : current ? "•" : stage.id}</span><span className="timeline-step-number">STEP {String(stage.id).padStart(2, "0")}</span><strong>{stage.label}</strong><span>{stage.short}</span>{current && <em>현재 단계</em>}</button>; })}</section>
    <section className="dashboard-lower"><div className="mini-panel"><div className="panel-head"><h3>주요 발주 구성</h3><span>이번 Cycle</span></div><div className="composition-row"><span>기기</span><div className="composition-bar"><b style={{ width: `${totalAmount ? (deviceAmount / totalAmount) * 100 : 0}%` }} /></div><strong>{Math.round(totalAmount ? (deviceAmount / totalAmount) * 100 : 0)}%</strong></div><div className="composition-row"><span>옵션·부품</span><div className="composition-bar"><b className="mint" style={{ width: `${totalAmount ? (optionAmount / totalAmount) * 100 : 0}%` }} /></div><strong>{Math.round(totalAmount ? (optionAmount / totalAmount) * 100 : 0)}%</strong></div></div><div className="mini-panel next-panel"><div className="panel-head"><h3>다음 확인 항목</h3><span>Action required</span></div><p>Flexibility Rule 및 MOQ 조정 항목을 검토한 후 기기 발주량을 확정하세요.</p><button className="text-button" onClick={() => onSelectStage(3)}>기기 발주량으로 이동 →</button></div></section>
  </div>;
}
