import type { WorkflowCycle } from "../../lib/types";

const money = (value: unknown) => `${Number(value ?? 0).toLocaleString("ko-KR")}원`;
const qty = (value: unknown) => Number(value ?? 0).toLocaleString("ko-KR");
export function getStageData(stageId: number, cycle: WorkflowCycle) {
  if (stageId === 0) return { rows: cycle.olRows as unknown as Record<string, unknown>[], columns: [{ key: "department", label: "영업부서" }, { key: "productName", label: "기종" }, { key: "category", label: "구분" }, { key: "needMonth", label: "필요월도" }, { key: "olQty", label: "OL 수량", format: qty }, { key: "status", label: "검증상태", format: (v: unknown) => <span className="badge ok">{String(v)}</span> }] };
  if (stageId === 1) return { rows: cycle.demandRows as unknown as Record<string, unknown>[], columns: [{ key: "source", label: "출처" }, { key: "name", label: "Pipeline / Deal" }, { key: "customer", label: "고객" }, { key: "productCode", label: "기종코드" }, { key: "needMonth", label: "출고월도" }, { key: "qty", label: "수량", format: qty }, { key: "decision", label: "결정", format: (v: unknown) => <span className={`badge ${v === "확정" ? "ok" : "warn"}`}>{String(v)}</span> }] };
  if (stageId === 2) return { rows: cycle.inventoryRows as unknown as Record<string, unknown>[], columns: [{ key: "category", label: "구분" }, { key: "productName", label: "품목" }, { key: "supplier", label: "Supplier" }, { key: "endingStock", label: "전월 말 재고", format: qty }, { key: "openPo", label: "Open PO", format: qty }, { key: "available", label: "가용재고", format: qty }, { key: "risk", label: "상태", format: (v: unknown) => <span className={`badge ${v === "정상" ? "ok" : "warn"}`}>{String(v)}</span> }] };
  if (stageId === 3) return { rows: cycle.deviceRecommendations as unknown as Record<string, unknown>[], columns: [{ key: "code", label: "기종코드" }, { key: "name", label: "기종" }, { key: "supplier", label: "Supplier" }, { key: "needMonth", label: "필요월도" }, { key: "demand", label: "확정수요", format: qty }, { key: "available", label: "가용재고", format: qty }, { key: "orderQty", label: "제안 발주량", format: qty }, { key: "amount", label: "발주금액", format: money }, { key: "result", label: "검증", format: (v: unknown) => <span className={`badge ${String(v) === "정상" ? "ok" : "warn"}`}>{String(v)}</span> }] };
  if (stageId === 4) return { rows: cycle.optionRecommendations as unknown as Record<string, unknown>[], columns: [{ key: "code", label: "품목코드" }, { key: "name", label: "옵션·소모품" }, { key: "supplier", label: "Supplier" }, { key: "needMonth", label: "필요월도" }, { key: "demand", label: "총 소요량", format: qty }, { key: "available", label: "가용재고", format: qty }, { key: "orderQty", label: "제안 발주량", format: qty }, { key: "amount", label: "발주금액", format: money }, { key: "result", label: "검증", format: (v: unknown) => <span className={`badge ${String(v) === "정상" ? "ok" : "warn"}`}>{String(v)}</span> }] };
  if (stageId === 5) return { rows: [{ item: "기기 발주금액", current: cycle.deviceRecommendations.reduce((a, x) => a + x.amount, 0), previous: 0, status: "승인 대기" }, { item: "옵션·부품·소모품", current: cycle.optionRecommendations.reduce((a, x) => a + x.amount, 0), previous: 0, status: "승인 대기" }] as Record<string, unknown>[], columns: [{ key: "item", label: "분석항목" }, { key: "current", label: "당월 발주금액", format: money }, { key: "previous", label: "전월 발주금액", format: money }, { key: "status", label: "승인상태", format: (v: unknown) => <span className="badge warn">{String(v)}</span> }] };
  if (stageId === 6) return { rows: [{ field: "PO번호", value: "PO-202608-001", status: "검증 전" }, { field: "Supplier", value: "Supplier A", status: "검증 전" }, { field: "최종 발주량", value: "30", status: "검증 전" }, { field: "납기요청일", value: "2026-09-25", status: "검증 전" }] as Record<string, unknown>[], columns: [{ key: "field", label: "FX-LIVE 필드" }, { key: "value", label: "값" }, { key: "status", label: "상태", format: (v: unknown) => <span className="badge muted">{String(v)}</span> }] };
  return { rows: cycle.inboundRows as unknown as Record<string, unknown>[], columns: [{ key: "poNumber", label: "PO번호" }, { key: "supplier", label: "Supplier" }, { key: "productName", label: "품목" }, { key: "orderedQty", label: "발주수량", format: qty }, { key: "shippedQty", label: "선적수량", format: qty }, { key: "eta", label: "도착예정" }, { key: "customs", label: "통관" }, { key: "poMatch", label: "PO Match", format: (v: unknown) => <span className="badge warn">{String(v)}</span> }, { key: "payment", label: "지급" }] };
}
